import { randomBytes, createHash } from 'crypto';

// Shared between RefreshToken, EmailVerificationToken, and
// PasswordResetToken — all three follow the same pattern: generate a
// high-entropy random token, send the RAW token to the client (in a
// cookie or an email link), and store only its HASH in the database.
//
// Why SHA-256 here and NOT Argon2 (which we use for passwords): Argon2 is
// deliberately slow, to make brute-forcing a low-entropy human-chosen
// password expensive. These tokens are the opposite case — 256 bits of
// cryptographically random data, generated by us, not chosen by a human.
// Brute-forcing a 256-bit random value is infeasible regardless of hash
// speed, so a fast, standard cryptographic hash is the correct and
// standard tool here. Using Argon2 for these would just be slow for no
// added security benefit.

export function generateOpaqueToken(): string {
  return randomBytes(32).toString('hex');
}

export function hashToken(rawToken: string): string {
  return createHash('sha256').update(rawToken).digest('hex');
}
